In [2]:
#Print the julia version
import numpy as np
np.version.version

'1.10.1'

In [64]:
from __future__ import division

In [3]:
# 3. Create a null vector of size 10
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [8]:
# 4. Create a null vector of size 10 but the fifth value which is 1
z = np.zeros(10)
z[5]=1
z

array([ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.])

In [15]:
# 5. Create a vector with values ranging from 10 to 99
z = np.arange(10,100)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [19]:
# 6. Create a 3x3 matrix with values ranging from 0 to 8
Z = np.arange(0,9).reshape((3,3))
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
# 7. Find indices of non-zero elements from [1,2,0,0,4,0]
np.nonzero([1,2,0,0,4,0])


(array([0, 1, 4]),)

In [34]:
# 8. Create a 3x3 identity matrix
Z = np.eye(3)
Z

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [41]:
# 9. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
a = np.zeros((5,5))
np.fill_diagonal(a,np.arange(1,6))
a

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.],
       [ 0.,  0.,  3.,  0.,  0.],
       [ 0.,  0.,  0.,  4.,  0.],
       [ 0.,  0.,  0.,  0.,  5.]])

In [ ]:
# 10. Create a 10x10x10 array with random values
np.random.rand(10,10,10)

In [72]:
# Novice
# 1. Create a 8x8 matrix and fill it with a checkerboard pattern
Z = np.zeros((8,8))
Z[1::2,::2] = 1
Z[0::2,1::2] =1
Z

array([[ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.]])

In [78]:
# 2. Create a 10x10 array with random values and find the minimum and maximum values
x = np.random.rand(10,10)
x.min(),x.max()

(0.00025891518720866369, 0.99850246764461847)

In [14]:
# 3. Create a checkerboard 8x8 matrix using the tile function
# numpy's tile equal to repmat
a = np.array([[1,0],[0,1]])
np.tile(a,(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [65]:
# 4. Normalize a 5x5 random matrix (between 0 and 1)
a = np.random.randint(1,10,(5,5))
m = a.mean(axis=0)
s = a.std(ddof =1, axis = 0)

(a-m)/s

array([[ 0.71395694, -0.74586985, -0.14804664,  1.4694161 , -0.67082039],
       [-1.36841747, -0.74586985,  0.96230317, -0.76665188,  1.56524758],
       [ 0.71395694, -0.4068381 , -1.62851306,  0.19166297,  0.4472136 ],
       [-0.77345335,  1.62735241,  0.59218657, -1.08609016, -0.67082039],
       [ 0.71395694,  0.2712254 ,  0.22206996,  0.19166297, -0.67082039]])

In [77]:
# 5. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a = np.random.randint(1,10,(5,3))
b = np.random.randint(2,12,(3,2))
print a,"\n", b, "\n", a.dot(b)

[[3 6 9]
 [8 8 2]
 [7 8 1]
 [1 9 6]
 [6 8 1]] 
[[10  2]
 [ 7 10]
 [ 8  2]] 
[[144  84]
 [152 100]
 [134  96]
 [121 104]
 [124  94]]


In [92]:
# 6. Create a 10x10 matrix with row values ranging from 0 to 9
a = np.zeros((10,10))
a += np.arange(0,10)
a

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [104]:
# 7. Create a vector of size 50 with values ranging from 0 to 1, both excluded
np.linspace(0,1,52)[1:-1]

array([ 0.01960784,  0.03921569,  0.05882353,  0.07843137,  0.09803922,
        0.11764706,  0.1372549 ,  0.15686275,  0.17647059,  0.19607843,
        0.21568627,  0.23529412,  0.25490196,  0.2745098 ,  0.29411765,
        0.31372549,  0.33333333,  0.35294118,  0.37254902,  0.39215686,
        0.41176471,  0.43137255,  0.45098039,  0.47058824,  0.49019608,
        0.50980392,  0.52941176,  0.54901961,  0.56862745,  0.58823529,
        0.60784314,  0.62745098,  0.64705882,  0.66666667,  0.68627451,
        0.70588235,  0.7254902 ,  0.74509804,  0.76470588,  0.78431373,
        0.80392157,  0.82352941,  0.84313725,  0.8627451 ,  0.88235294,
        0.90196078,  0.92156863,  0.94117647,  0.96078431,  0.98039216])

In [100]:
# 8. Create a random vector of size 100 and sort it
a = np.random.rand(100).sort()


In [107]:
# 9. Consider two random matrices A anb B, check if they are equal.
a = np.random.rand(2,2)
b = np.random.rand(2,2)
np.allclose(a,b)

False

In [108]:
# 10. Create a random  of size 1000 and find the mean value
np.random.rand(1000).mean()

0.50524488437090154

In [110]:
# Apprentice
# 1. Make an array immutable (read-only)
# nothing
a = np.random.rand(2,2)
a.flags.writeable = False


In [22]:
# 2. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates


In [9]:
# 3. Create random vector of size 100 and replace the maximum value by 0
a = np.random.rand(100)
a[a.argmax()] = 0
a

array([ 0.57666999,  0.72732024,  0.04072352,  0.73653747,  0.00777331,
        0.13336295,  0.36989461,  0.21403269,  0.76934523,  0.1553323 ,
        0.32959821,  0.48484355,  0.33188653,  0.45989222,  0.81604134,
        0.62600981,  0.96497731,  0.72327673,  0.56022076,  0.30511623,
        0.6662684 ,  0.68160544,  0.80453509,  0.66534696,  0.6143985 ,
        0.52672743,  0.94855916,  0.74519203,  0.3872801 ,  0.16390008,
        0.21283984,  0.5924899 ,  0.01994656,  0.37337735,  0.92816753,
        0.91013409,  0.06005621,  0.54899584,  0.25278213,  0.18175294,
        0.09545689,  0.96859687,  0.34939642,  0.59990907,  0.7008814 ,
        0.51329294,  0.51549874,  0.1742139 ,  0.03265794,  0.71292073,
        0.93690311,  0.69467052,  0.59684954,  0.82826241,  0.53775277,
        0.77805371,  0.70463505,  0.31117869,  0.85245035,  0.14368881,
        0.04313336,  0.62569511,  0.80686149,  0.14284927,  0.90924732,
        0.55779438,  0.73916289,  0.        ,  0.04409316,  0.02

In [13]:
# 4. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.
# There is not exist `meshgrid` officially
# see also. https://github.com/JuliaLang/julia/issues/4093
# assume using https://github.com/JuliaLang/julia/blob/master/examples/ndgrid.jl



In [11]:
# 5. Print the minimum and maximum representable value for each Numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
   print "{0} min: {1}".format(dtype,np.iinfo(dtype).min)
   print "{0} max: {1}".format(dtype,np.iinfo(dtype).max) 
for dtype in [np.float32, np.float64]:
   print "{0} min: {1}".format(dtype,np.finfo(dtype).min)
   print "{0} max: {1}".format(dtype,np.finfo(dtype).max)
   print "{0} eps: {1}".format(dtype,np.finfo(dtype).eps)


<type 'numpy.int8'> min: -128
<type 'numpy.int8'> max: 127
<type 'numpy.int32'> min: -2147483648
<type 'numpy.int32'> max: 2147483647
<type 'numpy.int64'> min: -9223372036854775808
<type 'numpy.int64'> max: 9223372036854775807
<type 'numpy.float32'> min: -3.40282346639e+38
<type 'numpy.float32'> max: 3.40282346639e+38
<type 'numpy.float32'> eps: 1.19209289551e-07
<type 'numpy.float64'> min: -1.79769313486e+308
<type 'numpy.float64'> max: 1.79769313486e+308
<type 'numpy.float64'> eps: 2.22044604925e-16


In [12]:
# 6. Create a structured array representing a position (x,y) and a color (r,g,b)
np.zeros(10, dtype = [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])


array([((0.0, 0.0), (0.0, 0.0, 0.0)), ((0.0, 0.0), (0.0, 0.0, 0.0)),
       ((0.0, 0.0), (0.0, 0.0, 0.0)), ((0.0, 0.0), (0.0, 0.0, 0.0)),
       ((0.0, 0.0), (0.0, 0.0, 0.0)), ((0.0, 0.0), (0.0, 0.0, 0.0)),
       ((0.0, 0.0), (0.0, 0.0, 0.0)), ((0.0, 0.0), (0.0, 0.0, 0.0)),
       ((0.0, 0.0), (0.0, 0.0, 0.0)), ((0.0, 0.0), (0.0, 0.0, 0.0))], 
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

In [16]:
# 7. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

r_vector = np.random.rand(100,2)


In [28]:
# 8. Generate a generic 2D Gaussian-like array



# Another solution
# Author: Billou Beilour


# One more solution
# Author: Billou Beilour


In [29]:
# 9. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value ?


In [30]:
# 10. Find the nearest value from a given value in an array


In [31]:
# Journyman
# 1. Consider the following file:
# 1,2,3,4,5
# 6,,,7,8
# ,,9,10,11
# How to read it ?


In [31]:
# 2. Consider a generator function that generates 10 integers and use it to build an array
# I can't translate this question

In [32]:
# 3. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices) ?


In [33]:
# 4. How to accumulate elements of a vector (X) to an array (F) based on an index list (I) ?


In [34]:
# 5. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors


In [35]:
# 6. Considering a four dimensions array, how to get sum over the last two axis at once ?


In [36]:
# 7. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices ?


In [37]:
# Craftsman
# 1. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
# I don't find any function like stride_tricks.as_stride


In [38]:
# 2. Consider a set of 100 triplets describing 100 triangles (with shared vertices), find the set of unique line segments composing all the triangles.



In [39]:
# 3. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C ?


In [7]:
# 4. How to compute averages using a sliding window over an array ?


In [6]:
# Artisan
# 1. Considering a 100x3 matrix, extract rows with unequal values (e.g. [2,2,3])


In [5]:
# 2. Convert a vector of ints into a matrix binary representation.


In [43]:
# Adept
# 1. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)
# TBS

In [44]:
# Expert
# 1. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B ?
# I can't execute numpy version...

In [45]:
# 2. Extract all the contiguous 3x3 blocks from a random 10x10 matrix.
# TBS

In [46]:
# 3. Extract all the contiguous 3x3 blocks from a random 10x10 matrix.
# There is Symmetric class in julia but immutable
# https://github.com/JuliaLang/julia/blob/master/base/linalg/symmetric.jl
# See also: https://github.com/JuliaLang/julia/pull/1533

In [4]:
# 4. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once ? (result has shape (n,1))


In [3]:
# Master
# 1. Given a two dimensional array, how to extract unique rows ?
